spring:
  rabbitmq:
    virtual-host: zxs
    username: zxs
    password: zxs123
    addresses: zxs-1
    port: 5672
turbine:
#集群或者监控多个使用
#  app-config: front-api,front-api2
  app-config: front-api
  aggregator:
    cluster-config: default
#监控相应集群，多个用逗号隔开
#    cluster-config: frontApi
  combine-host-port: true
  cluster-name-expression: ['default']
#表明监控的是自定义的集群
#  cluster-name-expression: metadata['cluster']
  instanceUrlSuffix: /actuator/hystrix.stream
eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/,http://eureka-server3:8763/eureka/
      defaultZone: http://zxs:zxs123@eureka-server1:8761/eureka/
    registry-fetch-interval-seconds: 60
  instance:
    lease-renewal-interval-in-seconds: 30