spring:
  datasource:
    hikari:
      username: zxs
      password: jfz123456
      jdbc-url: jdbc:mysql://zxs-1:3306/api?useUnicode=true&amp;characterEncoding=utf8&amp;mysqlEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
#    virtual-host: zxs
    username: zxs
    password: zxs123
    addresses: zxs-1
    port: 5672
  zipkin:
    sender:
      type: rabbit
    base-url: http://10.3.20.126:9411/
    locator:
      discovery:
        enabled: true
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
eureka:
  instance:
    hostname: front-api
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
#集群名字配置，turbine监控需要
#    metadata-map:
#      cluster: frontApi
  client:
    service-url:
      defaultZone: http://zxs:zxs123@eureka-server1:8761/eureka/
    registry-fetch-interval-seconds: 60
zxs:
  test: 测试远程配置