spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  security:
    user:
      password: zxs123
      name: zxs
    oauth2:
      client:
        provider:
---
spring:
  profiles: dev
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka-server1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
### 注册中心集群配置，以不同profile启动###
spring:
  profiles: server1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server1
  client:
    service-url:
      defaultZone: http://eureka-server2:8762/eureka/,http://eureka-server3:8763/eureka/

---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server2
  client:
    service-url:
      defaultZone: http://eureka-server2:8761/eureka/,http://eureka-server3:8763/eureka/
---
spring:
  profiles: server3
server:
  port: 8763
eureka:
  instance:
    hostname: eureka-server3
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/